### ISSUE TITLE
make x11vnc display at native resloution 

### ISSUE THREAD

**Issue by Mohamedemad4** [SenetSoftware/shiny-spoon#1]

**Comment by tou2** [comment]
There will be another major issue that I faced before that should also happen here. 
If the Ubuntu booted without a monitor attached to the machine it won't even load x11 and vnc won't work.

There should be a solution but I never tried it because ssh was enough in my case.

**Comment by tou2** [comment]
We shouldn't worry about the  booting issue for now because I will be using laptops for the testing and maybe the beta too.
